sudo: required
services:
  - docker
before_install:
####Install Google Cloud SDK
  - curl https://sdk.cloud.google.com || bash > /dev/null ;
  - source $HOME/google-cloud-sdk/path.bash.inc
####Install/Update kubectl in gcloud cli
  - gcloud components update kubectl
####Access google cloud account
  - gcloud auth activate-service-account --key-file service_account.json
