sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
####Decrypt the google service account encrypted file 
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
####Install Google Cloud SDK
#####  - curl https://sdk.cloud.google.com || bash --path-update > /dev/null ;
#####  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud version || true
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
#### Add gcloud to $PATH
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud version
####Install/Update kubectl in gcloud cli
  - gcloud components update kubectl
####Access google cloud account
  - gcloud auth activate-service-account --key-file service-account.json
####Set gcloud project name
  - gcloud config set project multi-k8s-337918
####Set gcloud zone
  - gcloud config set compute/zone asia-east1-b
####Set gcloud kubernetes cluster
  - gcloud container clusters get-credentials multi-cluster
####Set Docker login
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
####Build Test image
  - docker build -t rohitpant89/react-test -f ./client/Dockerfile.dev ./client

script:
### Run Testcases
  - docker run -e CI=true rohitpant89/react-test npm test 

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
